steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - training/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/ml-repo/distilbert-priority:latest
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/ml-repo/distilbert-priority:latest
options:
  machineType: E2_HIGHCPU_8
timeout: 1800s
